class Sources():
    sources = (
        "ABC News",
        "Al Jazeera English",
        "Ars Technica",
        "Associated Press",
        "Axios",
        "Bleacher Report",
        "Bloomberg",
        "Breitbart News",
        "Business Insider",
        "Buzzfeed",
        "CBS News",
        "CNN",
        "CNN Spanish",
        "Crypto Coins News",
        "Engadget",
        "ESPN",
        "ESPN Cric Info",
        "Fortune",
        "Fox News",
        "Fox Sports",
        "Google News",
        "Hacker News",
        "IGN",
        "Mashable",
        "Medical News Today",
        "MS Now",
        "MTV News",
        "National Geographic",
        "National Review",
        "NBC News",
        "New Scientist",
        "Newsweek",
        "New York Magazine",
        "Next Big Future",
        "NFL News",
        "NHL News",
        "Politico",
        "Polygon",
        "Recode",
        "Reddit /r/all",
        "TechCrunch",
        "TechRadar",
        "The American Conservative",
        "The Hill",
        "The Huffington Post",
        "The Next Web",
        "The Verge",
        "The Wall Street Journal",
        "The Washington Post",
        "The Washington Times",
        "Time",
        "USA Today",
        "Vice News",
        "Wired"
    )

    qcombobox_options = ["Select source(s)"] + [source for source in sources]